import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import { useAddUser, useGetUsers, useOnUserAdded } from '@shared/ui-library/hooks/useGraphql';
import { User } from '@shared/ui-library/types/graphql';
import Loading from '@shared/ui-library/components/Loading';
import Error from '@shared/ui-library/components/Error';
import UsersList from '@shared/ui-library/components/UsersList';
import Button from '@shared/ui-library/components/Button';

const Home: React.FC = () => {
  const [data, setData] = useState<User[]>([]);
  const { users, error, loading, refetch } = useGetUsers();
  const newUser = useOnUserAdded();
  const { addUser } = useAddUser();

  useEffect(() => {
    if (!error && !loading && users) {
      setData(users);
    }
  }, [users, error, loading]);

  useEffect(() => {
    const found = data.filter((i) => i.id === newUser?.id);
    if (newUser && found.length === 0) {
      setData([...data, newUser]);
    }
  }, [newUser, data]);

  const onRefreshPressed = () => {
    refetch();
  };

  const onAddFakeUserPressed = () => {
    addUser({
      variables: {
        userInput: { name: 'John', email: 'john@email.com' },
      },
    });
  };

  if (loading) {
    return <Loading />;
  }

  if (error) {
    return <Error text={error.message} />;
  }

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title" data-testid="page-title">
          All users
        </h1>
        <Button onPress={onRefreshPressed}>Manual Refresh</Button>
        <Button onPress={onAddFakeUserPressed}>Add fake user</Button>
        <UsersList data={data} />
      </main>
    </div>
  );
};

export default Home;
